repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # - repo: https://github.com/prettier/prettier
  #   rev: "v3.1.0" # Update this to the version of Prettier you are using
  #   hooks:
  #     - id: prettier
  #       files: ^frontend\/[^\/]+
  #       args: [--config, frontend/.prettierrc, --write, --plugin-search-dir=.]


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "requirements.txt"
      - id: check-yaml
      - id: check-added-large-files
