name: ci_frontend
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  backend:
    name: Run PR Frontend Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./frontend
        run: |
         pnpm install

      - name: Svelte Check
        working-directory: ./frontend
        run: pnpm svelte-check
